# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#[
# Examples:
#[
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
fishes= [
    ["Alewife", "Alosa pseudoharengus"],
    ["Amberjack", "Seriola dumerili"],
    ["Amberjack (yellowtail)", "Serola lalandi"],
    ["American eel", "Anguilla rostrata"],
    ["Arctic char", "Salvelinus alpinus"],
    ["Arctic grayling", "Thymallus arcticus"],
    ["Atlantic cod (Baltic)", "Gadus morhua"],
    ["Atlantic croaker (Baltic)", "Micropogonius undulatus" ],
    ["Atlantic herring", "Clupea harengus"],
    ["Atlantic halibut", "Hippoglossus hippoglossus" ],
    ["Atlantic mackerel", "Scomber scombrus"],
    ["Atlantic menhaden", "Brevoortia tyrannus" ],
    ["Atlantic seasnail", "Liparis atlanticus" ],
    ["Atlantic salmon", "Salmo salar"],
    ["Atlantic tomcod", "Microgadus tomcod"],
    ["Australian pilchard", "Sardinops sagax" ],
    ["Ayu", "Plecoglossus altivelis"],
    ["Baramundi perch", "Lates calcarifer"],
    ["Bengal danio (sind)", "Devario devario" ],
    ["Betta", "Betta splendens"],
    ["Bighead carp", "Aristichthys nobilis"],
    ["Black bullhead", "Ameiurus melas"],
    ["Black carp", "Mylopharyngodon piceus"],
    ["Black seabream (porgy)", "Hypophthalmichthys schlegeli" ],
    ["Bleak", "Alburnus alburnus"],
    ["Blue catfish", "Ictalurus furcatus"],
    ["Blue tilapia", "Oreochromus aureus"],
    ["Bluegill", "Lepomis macrochirus"],
    ["Bream (common)", "Abramis brama"],
    ["Brook trout", "Salvelinus fontinalis"],
    ["Brown bullhead", "Ameiurus nebulosus"],
    ["Brown-spotted grouper", "Epinephelus lovina" ],
    ["Brown trout", "Salmo trutta"],
    ["Channel catfish", "Ictalurus punctatus" ],
    ["Chinook salmon", "Oncorhynchus tshawytscha" ],
    ["Chum salmon", "Oncorhynchus keta"],
    ["Coho salmon", "Oncorhynchus kisutch"],
    ["Common carp", "Cyprinus carpio"],
    ["Common minnow (Eurasian)", "Phoxinus phoxinus" ],
    ["Common shiner", "Lulilus cornutus"],
    ["Cutthroat trout", "Oncorhynchus clarki" ],
    ["Dab (North Sea)", "Pleuronectus limanda" ],
    ["Damsel fish", "Chrysiptera spp."],
    ["Doctorfish", "Labroides dimidatus"],
    ["Emerald shiner", "Notropis atherinoides" ],
    ["Estuarine grouper", "Epinephelus tauvina" ],
    ["European catfish (wels)", "Silurus glanis" ],
    ["European perch", "Perca fluviatilis"],
    ["European flounder", "Platichthys flesus" ],
    ["European seabass", "Morone labrax"],
    ["European smelt", "Osmerus eperlanus"],
    ["European eel", "Anquilla anquilla"],
    ["Fathead minnow", "Pimephales promelas"],
    ["Formosa snakehead", "Channa maculata"],
    ["Gourami", "Osphronemus goramy"],
    ["Gilthead seabream", "Sparus auratus"],
    ["Gizzard shad", "Dorosoma cepedianum"],
    ["Glass knifefish", "Eigenmannia virescens" ],
    ["Gold sing wrasse", "Ctenolabrus rupestris" ],
    ["Golden shiner", "Notemigonus crysoleucas" ],
    ["Goldfish (Crucian carp)", "Carassius auratus" ],
    ["Grass carp", "Ctenopharyngodon idella"],
    ["Grayling", "Thymallus thymallus"],
    ["Greenback flounder", "Rhombosolea tapirina" ],
    ["Gudgeon (topmouth)", "Gobio gobio"],
    ["Gulf killifish", "Fundulus grandis"],
    ["Gulf menhaden", "Brevoortia patronus"],
    ["Guppy", "Poecilia reticulata"],
    ["Hardhead catfish", "Arius felis"],
    ["Ide (Orfe)", "Leuciscus idus"],
    ["Indian glassfish", "Chanda ranga"],
    ["Itipa mojarras", "Diapterus rhombeus"],
    ["Japanese catfish", "Silurus asotus"],
    ["Japanese eel", "Anguilla japonica"],
    ["Japanese striped knife jaw", "Oplegnathus faciatus" ],
    ["Kelp (red) grouper", "Epinephelus moora" ],
    ["Lake sturgeon", "Acinpenser fulvescens" ],
    ["Lake trout", "Salvelinus namaycush"],
    ["Macquarie perch", "Macquaria australasica" ],
    ["Masu (yamame, cherry salmon)", "Oncorynchus masou" ],
    ["Mozambique tilapia", "Oreochromis mossambicus" ],
    ["Mosquitofish", "Gambusia affinis"],
    ["Mountain galaxias", "Galaxias olidus"],
    ["Muskellunge", "Esox masquinongy"],
    ["Neon tetra", "Paracheirodon innesi"],
    ["Nile tilapia", "Oreochromis niloticus"],
    ["Northern anchovy", "Engraulis mordax"],
    ["Northern pike", "Esox lucius"],
    ["Olive flounder", "Paralichthys olivaceus" ],
    ["Pacific cod", "Gadus macrocephalus"],
    ["Pacific halibut", "Hippoglosus stenolepis" ],
    ["Pacific herring", "Clupea pallasi"],
    ["Pacific sardine", "Sardinops sagax"],
    ["Pacific white shrimp", "Penaeus vannamei" ],
    ["Pallid sturgeon", "Scaphirhynchus albus" ],
    ["Pearl danio", "Brachydanio albolineatus" ],
    ["Pejerrey", "Odonthestes banariensis"],
    ["Pinfish", "Lagodon rhomboides"],
    ["Pink salmon", "Oncorhynchus gorbuscha"],
    ["Plaice", "Pleuronectes platessa"],
    ["Whitespotted rabbitfish", "Siganus canaliculatus" ],
    ["Rabbitfish", "Siganus rivulatus"],
    ["Rainbow smelt", "Osmerus mordax"],
    ["Rainbow trout", "Oncorhynchus mykiss"],
    ["Rare minnow", "Gobiocypris rarus"],
    ["Red drum", "Sciaenops ocellatus"],
    ["Red seabream (Asia)", "Pagrus major"],
    ["Red seabream (New Zealand)", "Chrysophrys major" ],
    ["Redfin perch (European perch)", "Perca fluviatilis" ],
    ["Roach", "Rutilus rutilus"],
    ["Rudd", "Scardinius erythrophthalmus"],
    ["Sablefish", "Anoplopoma fimbria"],
    ["Seabream", "Sparus aurata"],
    ["Sea raven", "Hemitripterus americanus"],
    ["Shiner perch", "Cymatogaster aggregata" ],
    ["Shorthorn sculpin", "Myoxocephalus scorpius" ],
    ["Shortnose sturgeon", "Acipenser brevirostrum" ],
    ["Shovelnose sturgeon", "Scaphirhynchus platorynchus" ],
    ["Silver carp", "Hypophthalmichthys molitrix" ],
    ["Silver perch (North America)", "Bairdiella chrysoura" ],
    ["Silver perch (Australia)", "Bidyanus bidyanus"],
    ["Silver seatrout", "Cynoscion nothus"],
    ["Sockeye (kokanee)", "Oncorhynchus nerka" ],
    ["Snakehead (Chevron)", "Channa striata"],
    ["Sole (Dover)", "Solea solea"],
    ["Spotted grouper", "Epinephelus akaara"],
    ["Striped bass", "Morone saxatilis"],
    ["Striped jack (White trevaly)", "Caranx dentex" ],
    ["Striped mullet", "Mugil cephalus"],
    ["Striped snakehead", "Channa striata"],
    ["Striped trumpeter", "Latris lineata"],
    ["Tench", "Tinca tinca"],
    ["Tellina", "Tellina tenuis"],
    ["Threespot gourami", "Trichogaster trichopteru" ],
    ["Turbot", "Scophthalmus maximus"],
    ["Walking catfish", "Clarias batrachus"],
    ["Walleye", "Stizostedion vitreum"],
    ["Western blue shrimp", "Penaeus stylirostris" ],
    ["White perch", "Morone americana"],
    ["White bass", "Morone chrysops"],
    ["White bream (silver)", "Blicca bioerkna" ],
    ["White catfish", "Ameiurus catus"],
    ["Whitefish (ciscos)", "Coregonus spp."],
    ["White sturgeon", "Acipenser transmontanus" ],
    ["White seabass", "Atractoscion nobilis"],
    ["White sucker", "Catostoma commersoni"],
    ["Willow shiner", "Gnathopogon elongatus" ],
    ["Winter flounder", "Pleuronectus americanus" ],
    ["Yellow bullhead", "Ameiurus natalis"],
    ["Yellow perch", "Perca flavescens"],
    ["Yellowtail", "Seriola quinq"],
]

fishes.each do |common_name, species_name|
  Fish.create( common_name: common_name, species_name: species_name )
end